### ISSUE TITLE
OpenSwoole Version 22.0 Server CPU Count Function Error

### ISSUE THREAD

**Issue by kursadaltan** [fomo-framework/framework#8]
Openswoole Version 22.0 
When I trying php engineer server:start command I getted below errors. 

Fatal error: Uncaught Error: Call to undefined function swoole_cpu_num() in /var/www/php/vendor/fomo/framework/src/Helper/fomo.php:66
Stack trace:
#0 /var/www/php/config/server.php(14): cpuCount()
#1 /var/www/php/vendor/fomo/framework/src/Config/Config.php(28): require_once('/var/www/php/co...')
#2 /var/www/php/vendor/fomo/framework/src/Helper/fomo.php(59): Fomo\Config\Config->get('ssl.ssl_cert_fi...', NULL)
#3 /var/www/php/vendor/fomo/framework/src/Commands/Server/Start.php(87): config('server.ssl.ssl_...')
#4 /var/www/php/vendor/symfony/console/Command/Command.php(326): Fomo\Commands\Server\Start->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/php/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/php/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Fomo\Commands\Server\Start), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/php/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/php/engineer(98): Symfony\Component\Console\Application->run()
#9 {main}
  thrown in /var/www/php/vendor/fomo/framework/src/Helper/fomo.php on line 66

This problem is solved laravel octane. And I tried this update It's worked.

https://github.com/laravel/octane/pull/626/files

**Comment by kursadaltan** [comment]
This is solved already. But composer is not latest version I think.
